server:
  port: 80
eureka:
  client:
    register-with-eureka: true # 表示将自己注册进EurekaServer
    # 表示是否从Eureka抓取已有的注册信息，默认为true，单点无所谓，集群时候，必须设置成true，才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka # 单机
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka # 集群
spring:
  application:
    name: cloud-order-service
