server:
  port: 8001 # 端口号
spring:
  application:
    name: cloud-payment-service # 应用名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 数据源类型
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&charcaterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai # 数据库连接
    username: root # 数据库用户名
    password: root # 数据库密码
mybatis:
  mapper-locations: classpath:mapper/*.xml # mapper文件的位置
  type-aliases-package: com.atguigu.springcloud.entities # 实体类所在包
eureka:
  client:
    register-with-eureka: true # 表示将自己注册进EurekaServer
    # 表示是否从Eureka抓取已有的注册信息，默认为true，单点无所谓，集群时候，必须设置成true，才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka # 单机
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka # 集群
  instance:
    instance-id: payment8001 # 指定服务实例id
    prefer-ip-address: true # 访问路径可以显示IP地址
    # Eureka客户端向服务端发送心跳时间间隔，单位为秒，默认为30秒
    lease-renewal-interval-in-seconds: 1
    # Eureka服务端在接收到最后一次心跳后等待的时间上限，单位为秒，默认是90秒，超过后，微服务将被剔除
    lease-expiration-duration-in-seconds: 2
