server:
  port: 80
# 这里只把feign做客户端用，不注册进eureka
eureka:
  client:
    register-with-eureka: false # 表示是否将自己注册进EurekaServer默认为true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
# 设置feign客户端超时时间，OpenFeign默认支持Ribbon
ribbon:
  ReadTimeout: 5000 # 建立连接后，读取资源所用时间
  ConnectTimeout: 5000 # 建立连接所用时间
logging:
  level:
    # 指定监控哪个接口，以及监控的级别
    com.atguigu.springcloud.service.PaymentFeignService: debug
