server:
  port: 5555
spring:
  application:
    name: cloud-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: gateway-zuul-5555 # 指定服务实例ID
    prefer-ip-address: true # 访问路径可以显示IP地址
zuul:
  routes:
    serviceTempName.serviceId: cloud-provider-hystrix-payment
    serviceTempName.path: /provider8001/**
  ignored-services: cloud-provider-hystrix-payment
  prefix: /atguigu
# 默认情况下，actuator只会暴露health和info，让actuator暴露出routes, filters端点
management:
  endpoints:
    web:
      exposure:
        include: routes, filters
